# -*- coding: utf-8 -*-
"""Self_Learning_Concepts1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q066Jl3t75UJI35ax4xv8e4YxbYySwds

**Anomaly Detection:**

Anomaly Detection is a Machine Learning technique used to identify unusual or abnormal data points that differ significantly from normal observations.

These abnormal observations are called anomalies, outliers, or exceptions.

Anomaly Detection is widely used in banking, healthcare, cybersecurity, manufacturing, and IoT to detect fraud, security attacks, machine failures, and abnormal behavior.

**Importance**

Anomaly Detection is important because it helps to:


*   Detection fraud in banking.
*   Identify cyber attacks.
*   Detect machine failures.
*   Improve healthcare monitoring.
*   Prevent financial losses.
*   Improves system security.
*   Detect unusual customer behavior.

**Applications:**

*   Banking
*   Credit card Fraud Detection
*   ATM Fraud Detection
*   Healthcare
*   Disease Detection
*   ECG Monitoring
*   Cyber Security
*   Network Intrusion Detection
*   Malware Detection
*   Manufacturing
*   Machine Fault Detection
*   IoT
*   Sensor Failure Detection

**Workflow:**

Collect Data

       |

Data Cleaning

       |

Train Model

       |

Predict

       |

Detect Anomaly

       |

Visualize Results

**Advantages:**

*   Detects fraud quality.
*   Works with unlabeled data.
*   Improves securitty.
*   Detects rare events.
*   Suitable for large datasets.

**Disadvantages:**

*   Sensitive to noisy data.
*   May produce false alarms.
*   Difficult to choose contamination level.
*   Performance depends on data quality.
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble import IsolationForest

"""**Dataset:**

Most transactions are normal.

One transaction has a very high amount and is expected to be deyected as an anomaly.
"""

data={
    "Transaction Amount":[
        450,
        500,
        520,
        480,
        510,
        530,
        550,
        600,
        620,
        580,
        12000
    ]
}

df=pd.DataFrame(data)

df

print(df.shape)
print(df.info())
print(df.isnull().sum())

plt.figure(figsize=(8,5))

plt.scatter(
    df.index,
    df["Transaction Amount"],
    color="blue",
    s=80
)

plt.title("Transaction Amount Distribution")

plt.xlabel("Transaction Number")

plt.ylabel("Amount")

plt.grid()

plt.show()

model=IsolationForest(
    contamination=0.1,
    random_state=42
)

model.fit(df)

"""**Prediction:**

The model predicts:

1 -> Normal

-1 -> Anomaly
"""

df["Prediction"] = model.predict(df)

df

anomaly=df[df["Prediction"]==-1]

anomaly

colors=df["Prediction"].map({
    1:"green",
    -1:"red"
})

plt.figure(figsize=(9,5))

plt.scatter(
    df.index,
    df["Transaction Amount"],
    c=colors,
    s=120
)

plt.title("Anomaly Detection using Isolation Forest")

plt.xlabel("Transaction")

plt.ylabel("Transaction Amount")

plt.grid()

plt.show()

"""**REINFORCEMENT LEARNING(RL)**

Reinforcement Learning(RL) is a type of Machine Learning in which an agent learns how to make decisions by interating with an environment. The agent performs actions, receives rewards or penalties, and learns from its experiences to achieve the best possible outcome.
Unlike Supervised Learning, Reinforcement Learning does not require labeled data. Insted, it learns through a trial-and-error process.

**Definition:**
Reinforcement Learning is a Machine Learning technique where an agent learns the optimal behavior by taking actions in an environment and receiving rewards or penalties.

**Importance**:
Reinforcement Learning is important because it helps machines make intelligent decisions in situations where there is no predefined answer.

*   Learns through experience.
*   Makes sequential decisions.
*   Solves complex real-world problems.
*   Adapts to changing environments.
*   Improves performance over time.
*   Used in robotics and autonomous systems.
*   Helps optimize long-term rewards.

**Objectives:**
*   Learns the best action for every situation.
*   Maximize total rewards.
*   Minimize penalties.
*   Improve decision-making through experience.
*   Solve problems without labeled data.

**Workflow:**

Step 1:
Agent observes the current state.
|
Step2:
Agent chooses an action
|
Step3:
Environment changes.
|
Step4:
Environment gives reward.
|
Step5:
Agent updates its knowledge.
|
Step6:
Repeat until the task is completed.

**EXAMPLE:**
Robot Navigation

Suppose a robot wants to reach a destination.

If the robot moves correctly

Reward =+10

If it hits a wall

Penalty = -5

If it reaches the destination

Reward =+10

After many attempts, the robot learns the shortest path.

**Another Example:**
Self-Driving Car

State

Traffic signal

Action

Stop

Reward

Avoid accident

If the car crosses a red signal

Penalty

Negative reward

Eventually, the car learns safe driving.

**Types of Reinforcement Learning:**

**1.Positive Reinforcement:** Good behavior receives rewards.
Example: Dog gets a biscuit for following comments.

**2.Negative Reinforcement:** Agent learns to avoid penalties.
Example: Robot avoids obstacles.

**Applications:**

**Gaming**
*   Chess
*   Ludo
*   Go
*   Atari Games

**Robotics**
*   Robot navigation
*   Robot arm control

**Self-Driving Cars**
*   Lane detection
*   Traffic management
*   Parking

**Healthcare**
*   Personalized treatment planning
*   Drug recommendation

**Finance**
*   Stock trading
*   Portfolio optimization

**Recommendation Systems**
*   Movie recommendation
*   Product recommendation

**Smart Grid**
*   Energy optimization

**Manufacturing**
*   Process optimization
*   Resource allocation

**Advantages**

*   Learns automatically
*   No labeled data required
*   Solves complex problems
*   Continuously improves
*   Suitable for dynamic environments
*   Maximizes long-term rewards
*   Used in AI applications

**Disadvantages**

*   Requires large training time
*   Needs many interactions
*   High computational cost
*   Difficult to design rewards
*   Training may be unstable
*   Exploration can be expensive

**Difference Between Supervised and Reinforcement Learning**
"""

| Supervised Learning      | Reinforcement Learning     |
| ------------------------ | -------------------------- |
| Uses labeled data        | Uses rewards and penalties |
| Learns from examples     | Learns by trial and error  |
| Predicts outputs         | Makes decisions            |
| Requires correct answers | Learns through experience  |
| Example: Spam Detection  | Example: Robot Navigation  |

"""**Popular Reinforcement Learning Algorithms:**

**1. Q-Learning**

Learns the best action using a Q-table.

**2. SARSA**

Updates values based on the current policy.

**3.Deep Q Network (DQN)**

Uses Deep Learning with Q-Learning.

**4. Policy Gradient**

Learnspolicies directly.

**5. Actor-Critic**

Combines value-based and policy-based learning.
"""

import numpy as np
import random

rewards = np.array([
    [-1, -1, -1, -1, 0, -1],
    [-1, -1, -1, 0, -1, 100],
    [-1, -1, -1, 0, -1, -1],
    [-1, 0, 0, -1, 0, -1],
    [0, -1, -1, 0, -1, 100],
    [-1, 0, -1, -1, 0, 100]
])

print(rewards)

Q = np.zeros_like(rewards)
print(Q)

gamma = 0.8

for episode in range(1000):

    state = random.randint(0,5)

    while state != 5:

        possible_actions = []

        for action in range(6):

            if rewards[state, action] != -1:
                possible_actions.append(action)

        next_state = random.choice(possible_actions)

        future_rewards = np.max(Q[next_state])

        Q[state, next_state] = rewards[state, next_state] + gamma * future_rewards

        state = next_state

print(Q)

state = 2

print("Optimal Path")

while state != 5:

    print(state, end=" → ")

    state = np.argmax(Q[state])

print(5)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

plt.imshow(Q, cmap="Blues")

plt.colorbar()

plt.title("Q Table Heatmap")

plt.xlabel("Actions")

plt.ylabel("States")

plt.show()

print("The agent successfully learned the optimal path using Q-Learning.")

"""**Markov Decision Process(MDP)**

**Introduction:**
A Markov Decision Process (MDP) is a mathematical framework used to model decision-making problems where outcomes are partly controlled by the agent and partly determined by chance.
It is the foundation of Reinforcement Learning(RL) because it hepls an agent decide the best action to minimize rewards over time.
The key idea of an MDP is the Markov Property, which state that the future depends only on the current state and action, not the past history.
FOr example, a robot moving in a room decides its next move based only on its current position, not on the path it took to get there.

**Definition:**

A Morkov Decision Process (MDP) is defined by five components:
MDP = (S,A,P,R,Gamma)

where:

*   S = Set of States
*   A = Set of Actions
*   P = Transition Probability
*   R = Reward Function
*   (Gamma) = Discount Factor

**Components of MDP:**

**1.State(S)**

A state represents the current situation of the environment.
**Example:**

A robot is standing in Room A.

**2.Action (A)**

An action is a decision taken by the agent.

**Examples:**


*   Move Left
*   Move Right
*   Move Forward
*   Stop


**3.Transition Probability (P)**

Transition probability defines the chance of moving from one state to another after taking an action.

**Example:**

Robot moves Right

80% chance of reachinng Room B

20% chance of staying in Room A


**4.Reward (R)**

A reward is feedback received after performing an action.

**Example:**

Reached Goal --> +100

Hit Wall --> -10

**5.Dicount Factor**

The discount factor determines how much future rewards are valued.

its value ranges batween 0 and 1.

**Example:**

Gamma=0.9

The agent gives high importance to future rewards.

**Applications**:

**Robotics:** Robot Navigation

**Self-Driving Cars:** Path Planning

**Healthcare:** Treatment Planning

**Finance:** Investment Decisions

**Gaming:** Chess, Ludo, Go

**Recommendation Systems:** Netflix, Amazon, YouTube

**Advantages:**

*   Easy to model sequential decision problems.
*   Supports optimal decision making.
*   Foundation of Reinforcement Learning.
*   Handles uncertainty effectively.
*   Maximizes long-term rewards.

**Disadvantages:**

*   Large state space increases complexity.
*   Computationally expensive.
*   Difficult to define rewards.
*   Transition probabilities may not be known.
*   Not suitable for every real-world problem.
"""

import numpy as np
import matplotlib.pyplot as plt

reward = np.array([
[-1,-1,-1,-1,0,-1],
[-1,-1,-1,0,-1,100],
[-1,-1,-1,0,-1,-1],
[-1,0,0,-1,0,-1],
[0,-1,-1,0,-1,100],
[-1,0,-1,-1,0,100]
])

print(reward)

Q = np.zeros_like(reward)
print(Q)

gamma = 0.8

for episode in range(1000):

    state = np.random.randint(0,6)

    while state != 5:

        actions = []

        for i in range(6):

            if reward[state,i] != -1:

                actions.append(i)

        next_state = np.random.choice(actions)

        Q[state,next_state] = reward[state,next_state] + gamma*np.max(Q[next_state])

        state = next_state

print(Q)

state = 2

print("Optimal Path")

while state != 5:

    print(state,end=" → ")

    state = np.argmax(Q[state])

print(5)

plt.figure(figsize=(8,6))

plt.imshow(Q,cmap="YlGnBu")

plt.colorbar()

plt.title("Q Table Heatmap")

plt.xlabel("Actions")

plt.ylabel("States")

plt.show()

"""**Result**

The agent successfully learned the optimal path by maximizing rewards.

The Q-table contains the learned values for each state-action pair.

The heatmap visualizes these learned values.

**Q-Learninng Algorithm**

**Introduction:**

Q-Learning is a model-free Reinforcement Learning algorithm that helps an agent learn the best action to take in a particular state.

Unlike supervised learning, Q-Learning does not require labeled data. Instead, it learns by interacting with the environment and receiving rewards or penalties.

The objective of Q-Learning is to find the optimal policy, which helps the agent maximize the cumulative reward over time.

Q-Learning is widely used in robotics, game playing, autonomous vehicles, recommendation systems, and path planning.

**Importance:**



*   It learns without labeled data.
*   It finds the optimal action automatically.
*   It improves performance through experience.
*   It works in unknown environments.
*   It maximizes long-term rewards.
*   It forms the foundation of many advanced RL algorithms.

**Components:**

State(S): Represents the current situation.
Example: Robot at Position A

Action(A): Decision taken by the agent.
Example: Move Left, Move Right, Move Forward

Reward(R): Feedback after performing an action.

Example: Goal recahed

Reward =+100

Obstacle

Reward =-10

Q-Value: Represents the expected reward of taking an action in a state.

Q-Table: Stores all Q-values.

**Q-Learning Formula:**
"""

Q(s,a)=Q(s,a)+α[R+γmaxQ(s',a')−Q(s,a)]

Explanation

Q(s,a) → Current Q-value

α (Alpha) → Learning Rate

R → Reward

γ (Gamma) → Discount Factor

Max Q(s',a') → Maximum future reward

"""**Workflow:**

Initialize Q Table

         |
Observe State

         |
Choose Action

         |
Perform Action

         |
Receive Reward

         |
Update Q Table

         |
Repeat

         |
Optimal Policy

**Example:**

Suppose a robot wants to reach a destination.

Possible actions

*   Left
*   Right
*   Up
*   Down

If it reaches the goal

If it hits an obstacle

Reward =-10

After many episodes, the robot learns the shortest path.

**Applications:**


*   Robot Navigation
*   Chess AI
*   Self-Driving Cars
*   Warehouse Robots
*   Healthcare
*   Finance
*   Recommendation Systems
*   Drone Navigation
*   Smart Traffic Systems

**Advantages:**


*   Easy to underatand
*   Learns automatically
*   Finds optimal solutions.
*   Works without labeled data
*   Suitable for unknown environments.
*   Simple implementation

**Disadvantages:**


*   Slow for large envirinments.
*   Large Q-tables consume more memory
*   Exploration takes time
*   Difficult for continuous state spaces
*   Training may require many episodes

**Difference Between Q-Learning and SARSA**
"""

| Q-Learning                 | SARSA                       |
| -------------------------- | --------------------------- |
| Off-policy                 | On-policy                   |
| Uses maximum future reward | Uses actual next action     |
| Faster learning            | More conservative           |
| May converge faster        | Safer in risky environments |

import numpy as np
import random
import matplotlib.pyplot as plt

reward = np.array([
[-1,-1,-1,-1,0,-1],
[-1,-1,-1,0,-1,100],
[-1,-1,-1,0,-1,-1],
[-1,0,0,-1,0,-1],
[0,-1,-1,0,-1,100],
[-1,0,-1,-1,0,100]
])

print(reward)

Q=np.zeros_like(reward)
print(Q)

gamma = 0.8

for episode in range(1000):

    state = random.randint(0,5)

    while state != 5:

        actions = []

        for i in range(6):

            if reward[state,i] != -1:
                actions.append(i)

        next_state = random.choice(actions)

        Q[state,next_state] = reward[state,next_state] + gamma*np.max(Q[next_state])

        state = next_state

print(Q)

state = 2

print("Optimal Path")

while state != 5:

    print(state,end=" → ")

    state = np.argmax(Q[state])

print(5)

plt.figure(figsize=(8,6))

plt.imshow(Q,cmap="YlGnBu")

plt.colorbar()

plt.title("Q Table Heatmap")

plt.xlabel("Actions")

plt.ylabel("States")

plt.show()

"""**Difference Between RL, MDP AND Q-Learning**"""

| Topic                             | What it is                    | Focus                                                     | Code                                              |
| --------------------------------- | ----------------------------- | --------------------------------------------------------- | ------------------------------------------------- |
| **Reinforcement Learning (RL)**   | A branch of Machine Learning  | Overall concept of learning through rewards and penalties | Basic RL example or Gym environment               |
| **Markov Decision Process (MDP)** | Mathematical framework for RL | States, actions, rewards, probabilities                   | Transition matrix, reward matrix, value iteration |
| **Q-Learning**                    | An RL algorithm               | Learns the best action using a Q-table                    | Q-table update algorithm                          |

"""**Deep Q-Network (DQN):**

Introduction:

Deep Q-Network(DQN) is an advanced Reinforcement Learning algorithm that combines Q-Learning with Deep Neural Networks(DNN).

In traditional Q-Learning, a Q-table stores the Q-values for each state-action pair.

However, when the number of ststes becomes very large, maintaining a Q-table becomes impractical.

DQN overcome this limitation by replacing the Q-table with a Deep Neural Network that predicts Q-values for screen images.

Google DeepMind introduced DQN in 2015, and it successfully learned to play Atari games directly from screen images.

Why Do We Need DQN?

Traditional Q-Learning works well only for small environments.

For example:
A maze with 10 states --> Q-Learning works well.

A self-driving car with millions of states --> Q-table becomes impossible to store.

DQN solves this problem by using a Neural Network to estimate Q-values instead of storing them in a table.

**Definition:**

A Deep Q-Network (DQN) is a Reinforcement Learning algorithm that uses a Deep Neural Network to approximate the Q-value function and learn the optimal policy for an agent.

**Architecture of DQN:**



State

         |

Deep Neural Network

         |

Predicted Q-values

         |

Choose Best Actiob

         |

Envirinment

         |

Reward

         |

Update Network

**Difference Between Q-Learning and DQN**
"""

| Q-Learning              | DQN                           |
| ----------------------- | ----------------------------- |
| Uses Q-table            | Uses Neural Network           |
| Small state space       | Large state space             |
| Fast for small problems | Suitable for complex problems |
| No Deep Learning        | Uses Deep Learning            |

"""**Applications:**


*   Self-driving cars
*   Robotics
*   Game playing(Atari)
*   Smart traffic systems
*   Drone navigation
*   Warehouse automation
*   Healthcare
*   Recommendation systems

**Advantages:**


*   Handles large state spaces.
*   Uses Deep Learning
*   Learns complex behaviors
*   Better performance than Q-Learning
*   Suitable for real-world problems
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import matplotlib.pyplot as plt

states = np.array(
    [
        [0],
        [1],
        [2],
        [3],
        [4]
    ]
)

q_values = np.array(
    [
        [0.1,0.5],
        [0.3,0.8],
        [0.6,0.9],
        [0.8,1.0],
        [1.0,1.2]
    ]
)

model = Sequential([
    Dense(16,activation="relu",input_shape=(1,)),
    Dense(16,activation="relu"),
    Dense(2)
])

model.compile(
    optimizer="adam",
    loss="mse"
)

model.summary()

history = model.fit(
    states,
    q_values,
    epochs=100,
    verbose=0
)

prediction = model.predict(states)

print(prediction)

plt.figure(figsize=(8,5))

plt.plot(history.history["loss"])

plt.title("Training Loss")

plt.xlabel("Epoch")

plt.ylabel("Loss")

plt.grid(True)

plt.show()

plt.figure(figsize=(8,5))

plt.plot(prediction[:,0],label="Action 1")

plt.plot(prediction[:,1],label="Action 2")

plt.title("Predicted Q Values")

plt.xlabel("State")

plt.ylabel("Q Value")

plt.legend()

plt.grid(True)

plt.show()